sudo: required
dist: trusty
language: c
services:
  - docker
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -qq -y --no-install-recommends qemu-user-static binfmt-support
  - sudo update-binfmts --display qemu-arm
script:
  - uname -a
  - pwd
  - docker --version
  - make -version
  - cat Makefile
  - make --debug container-i386
  - make --debug container-amd64
  - make --debug container-i386-vpnserver
  - make --debug container-amd64-vpnserver
after_success:
  - make all-push
branches:
  only:
    - master