sudo: required
dist: trusty
language: c
services:
  - docker
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -qq -y --no-install-recommends qemu-user-static binfmt-support
  - ls /usr/bin/qemu-*-static
  - sudo update-binfmts --display qemu-arm
  - sudo update-binfmts --display qemu-aarch64
  # shutdown servies on Travis, which may have a memory impact
  # show memory usage before and after shutdown of services
  - sudo service --status-all
  - sudo free -m -t
  - sudo /etc/init.d/postgresql stop
  - sudo free -m -t
env:
  - ARCH=amd64
  - ARCH=i386
  - ARCH=armel
  - ARCH=rpi
  - ARCH=armhf
  - ARCH=aarch64
script:
  - uname -a
  - docker --version
  - make -version
  - make container-$ARCH container-$ARCH-vpnserver container-$ARCH-vpnbridge container-$ARCH-vpnclient
after_failure:
  # show memory usage again
  - sudo free -m -t
  # show actions of the OOM killer
  - sudo dmesg
deploy:
  provider: script
  skip_cleanup: true
  script: make push-$ARCH push-$ARCH-vpnserver push-$ARCH-vpnbridge push-$ARCH-vpnclient
  on:
    branch: master
branches:
  only:
    - master