#
# SoftEther VPN {{ARG_APP}} built from source for {{ARG_ARCH}}
#
FROM {{ARG_BASEIMAGE}}
MAINTAINER Diogo Quintela <dquintela@gmail.com>

ARG IMAGE_VERSION=0.0.0
ARG VCS_REF=HEAD
ARG VCS_URL=https://github.com/dquintela/docker-softether.git
ARG SCHEMA_USAGE=https://github.com/dquintela/docker-softether/blob/master/README.md
ARG SCHEMA_URL=https://github.com/dquintela/docker-softether

LABEL org.label-schema.name="softether-{{ARG_APP}}-{{ARG_ARCH}}" \
      org.label-schema.description="SoftEther VPN {{ARG_APP}} built from source for {{ARG_ARCH}}" \
      org.label-schema.usage="${SCHEMA_USAGE}" \
      org.label-schema.url="${SCHEMA_URL}" \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.vcs-url="${VCS_URL}" \
      org.label-schema.vendor="Diogo Quintela" \
      org.label-schema.version="${IMAGE_VERSION}" \
      org.label-schema.schema-version="1.0"

ENTRYPOINT ["/docker-softether/run-{{ARG_APP}}.sh"]
CMD ["--help"]
