#
# SoftEther VPN Server / Client / Bridge built from source for {{ARG_ARCH}}
#
FROM {{ARG_BASEIMAGE}}
MAINTAINER Diogo Quintela <dquintela@gmail.com>

# ENV like, but does not persist on final image
# Can be replaced by --build-arg on docker-build
ARG IMAGE_VERSION
ARG VCS_REF
ARG VCS_URL
ARG SCHEMA_USAGE
ARG SCHEMA_URL
ARG SOFTETHER_CPU=32bit
ARG DEBIAN_FRONTEND=noninteractive

# Persist on final image
ENV SOFTETHER_BIN="/usr/local/bin" \
	SOFTETHER_INSTALL="/usr/local/softether" \
	SOFTETHER_UPSTREAM_VERSION="{{ARG_UPSTREAM_VERSION}}"

COPY host-qemu /
COPY script /docker-softether/

# ethtool,iptables are used by vpnserver 
# Don't install iptables, need a privileged containers (let softether detect as not found) ??
# Check if --cap-add NET_ADMIN is enough
# https://github.com/SoftEtherVPN/SoftEtherVPN/search?utf8=%E2%9C%93&q=UnixExec&type=Code
# https://github.com/SoftEtherVPN/SoftEtherVPN/search?utf8=%E2%9C%93&q=UnixExecSilent&type=Code
# ca-certificates is because we are using --no-install-recommends
# --------------------------------------------------------------------------------------
# Instead of git clone (ot of memory in TravisCI), download the tarball for the ref
# https://developer.github.com/v3/repos/contents/#get-archive-link
# https://stackoverflow.com/questions/8377081/github-api-download-zip-or-tarball-link
#
# Replace
# git clone --verbose --depth=1 https://github.com/SoftEtherVPN/SoftEtherVPN.git /tmp/SoftEtherVPN \
# && cd /tmp/SoftEtherVPN \
# && git checkout {{ARG_UPSTREAM_VERSION}} \
#
# With (untar with striping of base directory)
# mkdir /tmp/SoftEtherVPN \
# cd /tmp/SoftEtherVPN \
# curl -L https://api.github.com/repos/SoftEtherVPN/SoftEtherVPN/tarball/{{ARG_UPSTREAM_VERSION}} | tar xf --strip=1
# --------------------------------------------------------------------------------------

RUN set -xe \
&& apt-get update \
&& apt-get install -q -y --no-install-recommends ca-certificates libreadline6 libssl1.0.0 libncurses5 ethtool iptables \
&& apt-get install -q -y --no-install-recommends build-essential curl libreadline6-dev libssl-dev libncurses5-dev \
&& mkdir /tmp/SoftEtherVPN \
&& cd /tmp/SoftEtherVPN \
&& curl -L https://api.github.com/repos/SoftEtherVPN/SoftEtherVPN/tarball/{{ARG_UPSTREAM_VERSION}} | tar xz --strip=1 \
&& cp src/makefiles/linux_${SOFTETHER_CPU}.mak Makefile \
&& make CC=gcc \
&& make install \
INSTALL_BINDIR=${SOFTETHER_BIN}/ \
INSTALL_VPNSERVER_DIR=${SOFTETHER_INSTALL}/vpnserver/ \
INSTALL_VPNBRIDGE_DIR=${SOFTETHER_INSTALL}/vpnbridge/ \
INSTALL_VPNCLIENT_DIR=${SOFTETHER_INSTALL}/vpnclient/ \
INSTALL_VPNCMD_DIR=${SOFTETHER_INSTALL}/vpncmd/ \
&& apt-get remove -y --auto-remove --purge build-essential curl libreadline6-dev libssl-dev libncurses5-dev \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* \
&& rm -rf /tmp/SoftEtherVPN \
&& chmod +x /docker-softether/*.sh \
&& rm /usr/bin/qemu-*-static # MUST LAST LINE 

# https://docs.docker.com/engine/reference/builder/#label#stopsignal
# STOPSIGNAL signal
# https://docs.docker.com/engine/reference/builder/#/healthcheck
# HEALTHCHECK
VOLUME /var/log/softether

# 443 for OpenVPN over TLS
# 500 4500 for L2TP/IPSec
# 1701 for L2TP tunnel
# 4500 for NAT traversal
# 5555 for SoftEtherVPN
EXPOSE 443/tcp 992/tcp 1194/tcp 1194/udp 5555/tcp 500/udp 4500/udp

# WORKDIR ${SOFTETHER_INSTALL}
WORKDIR /docker-softether

# Persist on final image
ENV SOFTETHER_IMAGE_VERSION="${IMAGE_VERSION}"

LABEL org.label-schema.name="softether-{{ARG_ARCH}}" \
      org.label-schema.description="SoftEther VPN Server / Client / Bridge built from source for {{ARG_ARCH}}" \
      org.label-schema.usage="${SCHEMA_USAGE}" \
      org.label-schema.url="${SCHEMA_URL}" \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.vcs-url="${VCS_URL}" \
      org.label-schema.vendor="Diogo Quintela" \
      org.label-schema.version="${IMAGE_VERSION}" \
      org.label-schema.schema-version="1.0"

ENTRYPOINT ["/docker-softether/run.sh"]
CMD ["--help"]
